version: '3'

services:
  postgres_link:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres_database:/var/lib/postgresql/data
    env_file:
      - ./.postgres_password 

  retrieve_sat_details_1:
    image: retrieve_sat_details
    env_file:
      - ./.honest_node_1/.env

  retrieve_sat_details_2:
    image: retrieve_sat_details
    env_file:
      - ./.honest_node_2/.env

  retrieve_sat_details_3:
    image: retrieve_sat_details
    env_file:
      - ./.honest_node_3/.env

  retrieve_sat_details_4:
    image: retrieve_sat_details
    env_file:
      - ./.bad_node_1/.env

  honest_node_1:
    image: smartcontract/chainlink:0.10.14
    ports:
      - "6687:6688"
    env_file:
      - ./.chainlink_common/.env
      - ./.honest_node_1/.env
    volumes:
      - ./.honest_node_1:/chainlink
      - ./.chainlink_common:/chainlink_common
    command: local n -p /chainlink_common/.password -a /chainlink_common/.api
    depends_on:
      - "postgres_link"
      - "retrieve_sat_details_1"

  honest_node_2:
    image: smartcontract/chainlink:0.10.14
    ports:
      - "6686:6688"
    env_file:
      - ./.chainlink_common/.env
      - ./.honest_node_2/.env
    volumes:
      - ./.honest_node_2:/chainlink
      - ./.chainlink_common:/chainlink_common
    command: local n -p /chainlink_common/.password -a /chainlink_common/.api
    depends_on:
      - "postgres_link"
      - "retrieve_sat_details_2"

  honest_node_3:
    image: smartcontract/chainlink:0.10.14
    ports:
      - "6685:6688"
    env_file:
      - ./.chainlink_common/.env
      - ./.honest_node_3/.env
    volumes:
      - ./.honest_node_3:/chainlink
      - ./.chainlink_common:/chainlink_common
    command: local n -p /chainlink_common/.password -a /chainlink_common/.api
    depends_on:
      - "postgres_link"
      - "retrieve_sat_details_3"

  bad_node_1:
    image: smartcontract/chainlink:0.10.14
    ports:
      - "6684:6688"
    env_file:
      - ./.chainlink_common/.env
      - ./.bad_node_1/.env
    volumes:
      - ./.bad_node_1:/chainlink
      - ./.chainlink_common:/chainlink_common
    command: local n -p /chainlink_common/.password -a /chainlink_common/.api
    depends_on:
      - "postgres_link"
      - "retrieve_sat_details_4"

  web_interface:
    image: web_server
    ports:
      - "8000:8000"
    env_file:
      - ./.env_web_interface
    depends_on:
      - "honest_node_1"
      - "honest_node_2"
      - "honest_node_3"
      - "bad_node_1"
